version: '2.4'
services:
  ml-toolkit:
    image: guyzsarun/ml-toolkit-gpu:latest
    ports:
      - 8888:8888
    container_name: 'ml-docker-gpu'
    restart: always
    runtime: nvidia
    volumes:
      - /home/guyzsarun/.jupyter/jupyter_notebook_config
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/notebook
    entrypoint: "jupyter lab --ip=0.0.0.0 --no-browser --port=8888 --allow-root --NotebookApp.token=TOKEN --NotebookApp.password=PASSWORD"